name: panel
description: "The web administration panel for the FF Alarm environment."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.1
  fluent_ui: 4.8.7
  shared_preferences: 2.2.3
  dio: 5.4.3+1
  archive: 3.4.10
  linked_scroll_controller: 0.2.0
  latlong2: 0.9.1
  flutter_color_utils: 0.0.1
  quickalert:
    path: ./packages/quickalert-1.1.0/
  flutter_map_cancellable_tile_provider:
    path: ./packages/flutter_map_cancellable_tile_provider-2.0.0/
  flutter_map:
    path: ./packages/flutter_map-6.0.1/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  lints: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
